language: java

jdk:
  - oraclejdk8

env:
  global:
    # BINTRAY_USER
    - secure: "MHvFWOdQ+35Tif2UHOTbOaY6du+43rIDW4aTb3kOJsYn2V9thNZpp4p2/fL4BHAD4T8a5nYvXPsvpTAkbmZcS9yTI7Ir2tpv61TwR69IAwRZVhU8B+IMJCX6mzvrZGHyUWNdRAgznZDZYiqFR5EhRJpEsxl5NleniUr3jBMkZRRegMjd5EBnCZppFvmXTvqSBFe9gq4Se7ba4MCGbG/7lyhPudgg52CVGTPQajaGw8+ctxJLgvNBYDbhVdnoHAY2xAidKdQm8u3Jx+uiSZ4vdyJYRwqh+7+6E2tl7tCoW2ZGm3dT481Gr2IPDIbAFzxd5d2+mF7jQPY0Q7CgRmHWUajFfRVgDXGqpcWttKzsTgO4ieozbgVo8oSRR2Ovo031G9KKSTaqB0SNra5Ctqv9dbC+cG33JySeQLp/jcacHOJYIH/AK/du2LLgEQFXdEePizfjglDryndA7+Tfth+oNWP0azgzdpP0OfgOYDP+S8YMNB1g2eXFX4wmx9TvEYaqeHKEyKcD5UoNmPHw1Y6dSktRgCsucN3MGwc5tMK5cmL/UvvQJQmm/yoXFFViB9jZAr4I2VyYTW0pxiKVSRbXp5v/x8C1Ef271tgReAFB6RHWyH1QrEI2RVnRz0ZsW1HdPVTW36r8avX0ybGPi5jdlJKGD7K8qulDx8lrvg5J770="
    # BINTRAY_KEY
    - secure: "lSz+lgCJnQmdk3JK4o0fBK8EJNZ+D7mKAtCXFrYT9Dq2RQXXPnaw3Rzt4GotQWwTplfKqlT70xRVKjne5kK89OlGAnxoILxE4LBcdAoHk5Y9J4H6xG49wS1NODi/woZfYLo2CG9QG71Y4daAG44LxD/s86ZTKOCwoYHAhzbcxpZGqbfhOcuYiXYDdsWsfJ35epCg8EpWjkB95eE8rrLPh7FiHL4Jgpsf5uFbpNsmQ/hZ7MrYGuLRQt1acvxeSEutf4sRpMYDNSQZyzFAEBDAJmiNal0jQnh8ZMDDXJMx7EeyFXxZhbGy+zaG1wff20trW12Ps5Jlj54/CfqxUU7HXitthE9uzeMwprN4sA+q+nm5fkRmnkl9//aXAO4L7RRzlKsHswWRhizXisJ5gU5p6qLgicc/74JNWmdaeKrAl/WM5ZcE/KApI1VJQBnazsM751nj/xZNyYvvjAdS65D5S9KNBgEtsvIefoEhYdH0FLTekEDFXxhK0rSVoZCIJQA3MmAE4zG+qVo0PtGTyq5/bPK0P2imWKkFwt+v2drfOlNhOKiFX6awhxltoIH3dc+bZwHp1jje2pO69WBMSB8QsdEfZLDGoEjNIg7CrLPFJVfcYbbxTHcu71dPPVNdfd9PYlc/gRhkVyNcs0i30IguYboJakgYUmHfIva7k3V1HCY="
    # GPG_PASSPHRASE
    - secure: "hY+1Zm9671BvBuTQNxPC0nx58oUkKRBMIRHWug7YLPcTmj2b2cpX9z13FG4UQUvjYlyMTxWl/jMfL8fbtthyiFLGx9LNEgHzPg5HsxAEXkk6p/nT5vMKnEeNjy8wnfdE7X+ild810TUCp1t5ictMz6CtpueW+w6w3KXZVZ1hjg2xYEYpeMGoZeniaifaX2t2nVCqAxxOeCY/LVFQSUdwb6lREbU7bdpt+rSVtHUMKxxdcs6RI02B2eR816jl1kHXfShKTjlvcZw4broO4g7nDYYZdx5am+FbQSYhzqkkmOBPFzyp8aoKjDplrS+sM8fI6dBBEyPcoKTOqjM33PQMg272TNTR/nNCtuZQWxA6IRdITsRHfAQ+UGnSEbGm9xPhY/hvp2CMvRyUJ1hj9MbBwSVBarOMlk/bAbeXLR0GcetkRfPe2hGxuqthWKr/fGfPapdiROJRRBUj7AID445Ot3EKg3ix36fY/EcLwDWcKeCYgNXO+aOGju7UUP1rrR88+Pw9Z4SdvE5U8bYi9JfQuww/ObJmsdoIyLGZRDTy/zuKu7Gr4WanlNAtzEWAKjFLPMTSuGHhp4S6ZPpQwFMhsrcL3IuGcrw66xQsJZXBbxdf3xqyYECo4lrMUvtFHsYn4e6icyGXYvCqkXJKqE+uX+evr5eWGrrkFqFAW6UqbGY="

install: ./gradlew clean
script: ./gradlew test

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    on:
      tags: true

cache:
  directories:
    - ~/.gradle/
